# Base server provisioning playbook
---
- name: Base Setup
  hosts: localhost
  roles:
    - { role: geerlingguy.repo-epel }
    - { role: geerlingguy.repo-remi }
    - { role: geerlingguy.git }
    - { role: geerlingguy.apache }
    - { role: geerlingguy.php }
  post_tasks:
    - name: Clone app repository
      git:
        repo: https://github.com/mamchenkov/aws-example.git
        version: master
        dest: /var/www/aws-example
    - name: Install composer dependencies
      command: bin/composer install
      args:
        chdir: /var/www/aws-example/app
    - name: Create .env file
      copy:
        src: /var/www/aws-example/app/.env.example
        dest: /var/www/aws-example/app/.env
    - name: Remove /var/www/html directory
      file:
        state: absent
        path: "/var/www/html"
    - name: Symlink /var/www/html to app webroot
      file:
        state: link
        force: yes
        path: "/var/www/html"
        src: "/var/www/aws-example/app/webroot"
