# Base server provisioning playbook
---
- name: Base Setup
  hosts: localhost
  roles:
    - { role: geerlingguy.repo-epel }
    - { role: geerlingguy.repo-remi }
    - { role: geerlingguy.git }
    - { role: geerlingguy.apache }
    - { role: geerlingguy.php }
  post_tasks:
    - name: Clone app repository
      git:
        repo: https://github.com/mamchenkov/aws-example.git
        version: master
        dest: /var/www/aws-example
    - name: Install composer dependencies
      shell: ./bin/composer install
      args:
        chdir: /var/www/aws-example/app
      environment:
        HOME: "/root"
    - name: Create .env file
      copy:
        src: /var/www/aws-example/app/.env.example
        dest: /var/www/aws-example/app/.env
    - name: Set WEB_HOST in .env file
      lineinfile:
        path: /var/www/aws-example/app/.env
        regexp: '^WEB_HOST='
        line: "WEB_HOST={{webhost}}"
        state: present
      when: webhost is defined
    - name: Set DB_HOST in .env file
      lineinfile:
        path: /var/www/aws-example/app/.env
        regexp: '^DB_HOST='
        line: "DB_HOST={{dbhost}}"
        state: present
      when: dbhost is defined
    - name: Set DB_NAME in .env file
      lineinfile:
        path: /var/www/aws-example/app/.env
        regexp: '^DB_NAME='
        line: "DB_NAME={{dbname}}"
        state: present
      when: dbname is defined
    - name: Set DB_USER in .env file
      lineinfile:
        path: /var/www/aws-example/app/.env
        regexp: '^DB_USER='
        line: "DB_USER={{dbuser}}"
        state: present
      when: dbuser is defined
    - name: Set DB_PASS in .env file
      lineinfile:
        path: /var/www/aws-example/app/.env
        regexp: '^DB_PASS='
        line: "DB_PASS={{dbpass}}"
        state: present
      when: dbpass is defined
    - name: Remove /var/www/html directory
      file:
        state: absent
        path: "/var/www/html"
    - name: Symlink /var/www/html to app webroot
      file:
        state: link
        force: yes
        path: "/var/www/html"
        src: "/var/www/aws-example/app/webroot"
